package com.example.eCommerce.prac1.order.model;

import com.example.eCommerce.prac1.user.model.UserDTO;
import lombok.Data;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Data
public class OrderDTO {
    private Long id;
    private LocalDateTime date;
    /*orderNumber will be autogenerated*/
    private String orderNumber;
    /*here customer will be the loggedIn user*/
    private UserDTO customer;
    @NotBlank(message = "Shipping address should not be empty.")
    private String shippingAddress;
    private Double totalPrice = 0.0;
    private Double totalQty = 0.0;
    @NotEmpty(message = "select at least one product to place order.")
    private List<OrderDetailsDTO> orderDetails = new ArrayList<>();
}
